name: AntiAntiSwearFilter
main: dktapps\AntiAntiSwearFilter\Main
version: 0.1.0
api: [3.0.0]
load: POSTWORLD
author: dktapps
description: Circumvents Microsoft's terrible Minecraft built-in chat filter
website: https://github.com/dktapps/AntiAntiSwearFilter
