name: Uncensor
main: dktapps\Uncensor\Main
version: 0.2.0
api: [3.0.0, 4.0.0]
load: POSTWORLD
author: dktapps
description: Circumvents Microsoft's terrible Minecraft built-in chat filter
website: https://github.com/dktapps/Uncensor
